version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: globi_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "mix deps.get && mix ecto.setup && mix phx.server"

volumes:
  db_data:
